version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: tools/Dockerfile
    working_dir: /opt/service
    container_name: api
    environment:
      - HOME_DIR=/opt/service
      - CGO_ENABLED=0
      - PORT=8080
    volumes:
      - .:/opt/service/
      - .go:/go
    ports:
      - "8080:8080"
      - "8081:8081"

 